[2022-12-13 22:28:52,628][FLSim.builder][INFO] - benchmark.ctx.synthetic has created !
[2022-12-13 22:28:52,643][FLSim.builder][INFO] - benchmark.model.leaf.SyntheticMLP has created !
[2022-12-13 22:29:20,326][FLSim.builder][WARNING] - Traceback (most recent call last):
  File "D:\CodeSoftwares\Anaconda\lib\site-packages\cachetools\__init__.py", line 66, in __getitem__
    return self.__data[key]
KeyError: 'f_00000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\Python\flsim\utils\cache.py", line 23, in __missing__
    self[key] = self.read_disk(key)
  File "D:\Project\Python\flsim\utils\cache.py", line 44, in read_disk
    raise KeyError(key)
KeyError: 'f_00000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\Python\flsim\benchmark\builder.py", line 60, in build_trainer
    trainer = getattr(importlib.import_module(md), name)(net, fds, **args)
  File "D:\Project\Python\flsim\trainer\core\proto.py", line 32, in __init__
    self._init()
  File "D:\Project\Python\flsim\trainer\core\proto.py", line 232, in _init
    self._init_group()
  File "D:\Project\Python\flsim\trainer\core\proto.py", line 220, in _init_group
    self._init_group_hook()
  File "D:\Project\Python\flsim\trainer\algorithm\cfl\fedcluster.py", line 33, in _init_group_hook
    labels = self._cluster(cids)
  File "D:\Project\Python\flsim\trainer\algorithm\cfl\fedcluster.py", line 41, in _cluster
    M = self.kl_distance(cids, 1.)
  File "D:\Project\Python\flsim\trainer\algorithm\cfl\fedcluster.py", line 77, in kl_distance
    self._cache[cid]['logit'] = self._model(data) / temp
  File "D:\CodeSoftwares\Anaconda\lib\site-packages\cachetools\__init__.py", line 209, in __getitem__
    value = cache_getitem(self, key)
  File "D:\CodeSoftwares\Anaconda\lib\site-packages\cachetools\__init__.py", line 68, in __getitem__
    return self.__missing__(key)
  File "D:\Project\Python\flsim\utils\cache.py", line 26, in __missing__
    raise KeyError(key)
KeyError: 'f_00000'

[2022-12-13 22:29:20,326][FLSim.__main__][DEBUG] - Traceback (most recent call last):
  File "D:\CodeSoftwares\Anaconda\lib\site-packages\cachetools\__init__.py", line 66, in __getitem__
    return self.__data[key]
KeyError: 'f_00000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\Python\flsim\utils\cache.py", line 23, in __missing__
    self[key] = self.read_disk(key)
  File "D:\Project\Python\flsim\utils\cache.py", line 44, in read_disk
    raise KeyError(key)
KeyError: 'f_00000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\Python\flsim\benchmark\builder.py", line 60, in build_trainer
    trainer = getattr(importlib.import_module(md), name)(net, fds, **args)
  File "D:\Project\Python\flsim\trainer\core\proto.py", line 32, in __init__
    self._init()
  File "D:\Project\Python\flsim\trainer\core\proto.py", line 232, in _init
    self._init_group()
  File "D:\Project\Python\flsim\trainer\core\proto.py", line 220, in _init_group
    self._init_group_hook()
  File "D:\Project\Python\flsim\trainer\algorithm\cfl\fedcluster.py", line 33, in _init_group_hook
    labels = self._cluster(cids)
  File "D:\Project\Python\flsim\trainer\algorithm\cfl\fedcluster.py", line 41, in _cluster
    M = self.kl_distance(cids, 1.)
  File "D:\Project\Python\flsim\trainer\algorithm\cfl\fedcluster.py", line 77, in kl_distance
    self._cache[cid]['logit'] = self._model(data) / temp
  File "D:\CodeSoftwares\Anaconda\lib\site-packages\cachetools\__init__.py", line 209, in __getitem__
    value = cache_getitem(self, key)
  File "D:\CodeSoftwares\Anaconda\lib\site-packages\cachetools\__init__.py", line 68, in __getitem__
    return self.__missing__(key)
  File "D:\Project\Python\flsim\utils\cache.py", line 26, in __missing__
    raise KeyError(key)
KeyError: 'f_00000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\Python\flsim\benchmark\starter.py", line 27, in run
    trainer = build_trainer(tn, net, fds, cfg.trainer.args)
  File "D:\Project\Python\flsim\benchmark\builder.py", line 71, in build_trainer
    raise ImportError(f'No such trainer: {name}')
ImportError: No such trainer: FedCluster

